#! /usr/bin/env zsh


# npm
export NPM_CONFIG_USERCONFIG="$HOME/.config/npm/config"

export ZPLUG_HOME=/usr/share/zsh/scripts/zplug
export QT_QPA_PLATFORMTHEME="qt5ct"
export EDITOR=nvim
export PATH="$HOME/.local/share/npm/bin:$HOME/.cargo/bin:$HOME/.local/bin:$PATH"

