#!/usr/bin/env zsh

# === Options ===

#setopt correct                                                 # Auto correct mistakes
setopt extendedglob                                             # Extended globbing. Allows using regular expressions with *
setopt nocaseglob                                               # Case insensitive globbing
setopt rcexpandparam                                            # Array expension with parameters
setopt nocheckjobs                                              # Don't warn about running processes when exiting
setopt numericglobsort                                          # Sort filenames numerically when it makes sense
setopt nobeep                                                   # No beep
setopt appendhistory                                            # Immediately append history instead of overwriting
setopt histignorealldups                                        # If a new command is a duplicate, remove the older one
setopt autocd                                                   # if only directory path is entered, cd there.

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'       # Case insensitive tab completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"         # Colored completion (different colors for dirs/files/etc)
zstyle ':completion:*' rehash true                              # automatically find new executables in path 
# Speed up completions
zstyle ':completion:*' accept-exact '*(N)'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
HISTFILE=~/.zhistory
HISTSIZE=1000
SAVEHIST=500
WORDCHARS=${WORDCHARS//\/[&.;]}                                 # Don't consider certain characters part of the word


# === Plugin Management ===

source "$HOME/.config/shell/plugins"

# === Shell Parts ===

source "$HOME/.config/shell/exports"
source "$HOME/.config/shell/aliases"
source "$HOME/.config/shell/functions"
#source "$HOME/.config/shell/external"

# === Local Variables and Overrides ===

if [[ -f "$HOME/.shell_env_local" ]]; then
  source "$HOME/.shell_env_local"
fi

# opam configuration
test -r /home/ivan/.opam/opam-init/init.zsh && . /home/ivan/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
